mockservice:
  sleepSecOrigin : 1
  sleepSecBound: 4
server:
  connection-timeout: 10000
  compression:
    enabled: false
  tomcat:
    max-connections: 960
    max-threads: 400
    min-spare-threads: 350
    accept-count: 100
  port: 8081
camel:
  springboot:
    name: CamelaRestMockService
management:
  port: 8083
endpoints:
  enabled: false
  health:
    enabled: true
