spring:
    main:
      banner-mode: "off"
mockservice:
  sleepSecOrigin : 1
  sleepSecBound: 4
server:
  connection-timeout: 10000
  compression:
    enabled: false
  tomcat:
    max-connections: 400
    max-threads: 200
    min-spare-threads: 150
    accept-count: 100
  port: 8081
camel:
  springboot:
    name: CamelaRestMockService
management:
  port: 8083
endpoints:
  enabled: false
  health:
    enabled: true
