mockservice:
  sleepSecOrigin : 1
  sleepSecBound: 4
server:
  connection-timeout: 10000
  compression:
    enabled: false
  tomcat:
    max-connections: 2400
    max-threads: 1200
    min-spare-threads: 1000
    accept-count: 300
  port: 8081
camel:
  springboot:
    name: CamelaRestMockService
management:
  port: 8083
endpoints:
  enabled: false
  health:
    enabled: true
