spring:
  main:
    banner-mode: 'off'
mockservice:
  sleepSecOrigin: 1
  sleepSecBound: 4
server:
  port: 8080
camel:
  springboot:
    name: CamelaRestMockService
endpoints:
  enabled: true
  health:
    enabled: true