spring:
  metrics:
    export:
      enabled: false
  main:
    banner-mode: 'off'
mockservice:
  sleepSecOrigin: 1
  sleepSecBound: 4
server:
  tomcat:
    ajp-port: 8081
  port: 8080
camel:
  springboot:
    name: CamelaRestMockService
endpoints:
  enabled: true
  health:
    enabled: true
  metrics:
    filter:
      enabled: false
    enabled: false
 