mockservice:
  sleepSecOrigin : 1
  sleepSecBound: 4
server:
  port: 8081
camel:
  springboot:
    name: CamelaRestMockService
management:
  port: 8083
endpoints:
  enabled: false
  health:
    enabled: true